import { MappingRule } from "./types";

export const MAPPING_RULES: MappingRule[] = [
  {
    account: "101300000",
    concept: "Share",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "104100000",
    concept: "Reserves",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "104500000",
    concept: "Reserves",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "119000000",
    concept: "Prior periods' profit and loss",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "120000000",
    concept: "Prior periods' profit and loss",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "129000000",
    concept: "Prior periods' profit and loss",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "164000000",
    concept: "LT debts with financial institutions",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "164120000",
    concept: "LT debts with financial institutions",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "164130000",
    concept: "LT debts with financial institutions",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "164140000",
    concept: "LT debts with financial institutions",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "164150000",
    concept: "LT debts with financial institutions",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "168110000",
    concept: "LT debts with financial institutions",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "168120000",
    concept: "Other LT financial liabilities",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "168130000",
    concept: "LT debts with financial institutions",
    grandeCategorie: "Equity & Long-term Funding",
    sousCategorie: "Capital & Reserves",
  },
  {
    account: "205000000",
    concept: "Licences",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "218300000",
    concept: "IT equipment",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "232000000",
    concept: "Intangible assets - In progress",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "275110000",
    concept: "Deposits & Guarantees",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "275120000",
    concept: "Deposits & Guarantees",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "275130000",
    concept: "Deposits & Guarantees",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "275140000",
    concept: "Deposits & Guarantees",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "280500000",
    concept: "Licences",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "281830000",
    concept: "Amortisation",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "657000000",
    concept: "Amortization of tangible assets",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "408100000",
    concept: "Other ST accruals payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "401000000",
    concept: "Account Payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Short-term Debt",
  },
  {
    account: "411000000",
    concept: "Account Receivable",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "421000000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "424000000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "425100000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "428200000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "431000000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "437020000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "437030000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "437080000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "437200000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "437210000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "437300000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "437410000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "437500000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "437510000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "437800000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "438000000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "438200000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "438600000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "438610000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "438620000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "441710000",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "442100000",
    concept: "Other debts with PA",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "444000000",
    concept: "Taxes debitors",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "445100000",
    concept: "Other debts with PA",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445710090",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445200000",
    concept: "Other debts with PA",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445622000",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445623000",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445624000",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445640000",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445660000",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445661000",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445662100",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445662200",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445670000",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445740000",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445800000",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445830000",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "445860000",
    concept: "Public entities, other",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "448630000",
    concept: "Personnel payable",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "462000000",
    concept: "Trade debtors",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "467100000",
    concept: "Other ST debts",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "467000000",
    concept: "Other ST debts",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
  {
    account: "471600300",
    concept: "Items pending application",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "471600500",
    concept: "Items pending application",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "471600600",
    concept: "Items pending application",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "471600800",
    concept: "Items pending application",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "471700300",
    concept: "Items pending application",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "471700500",
    concept: "Items pending application",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "471700600",
    concept: "Items pending application",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "471700800",
    concept: "Items pending application",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "477000000",
    concept: "Items pending application",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "508000000",
    concept: "Financial Investments - ST",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "508010000",
    concept: "Financial Investments - ST",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "508020000",
    concept: "Financial Investments - ST",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "508030000",
    concept: "Financial Investments - ST",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "508040000",
    concept: "Financial Investments - ST",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "512100100",
    concept: "Cash",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "512100200",
    concept: "Cash",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "512100300",
    concept: "Cash",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "512100400",
    concept: "Cash",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "512100600",
    concept: "Cash",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "512100800",
    concept: "Cash",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "512100900",
    concept: "Cash",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "512400500",
    concept: "Cash",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "512400700",
    concept: "Cash",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "580000000",
    concept: "Cash",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "508050000",
    concept: "Financial Investments - ST",
    grandeCategorie: "Current Assets",
    sousCategorie: "Taxes & Other Receivables",
  },
  {
    account: "604000000",
    concept: "Studies & Documentation",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "606300000",
    concept: "Other IT costs",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "606400000",
    concept: "Other G&A expenses",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "607000000",
    concept: "Rent",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "613200000",
    concept: "Rent",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "613511000",
    concept: "Other R&D Services",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "622630001",
    concept: "Other G&A Services",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "613400000",
    concept: "Cloud Computing",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "613500000",
    concept: "Software licences Dev & R&D",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "613510000",
    concept: "Software licences Dev & R&D",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "613520000",
    concept: "Software licences G&A",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "613530000",
    concept: "Software licences M&S",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "616000000",
    concept: "Essential Services (Insurances, Phone, Connectivity)",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "618500000",
    concept: "Events M&S",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "621000000",
    concept: "HR Contractors",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "621010000",
    concept: "Studies & Documentation",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "621400000",
    concept: "HR EOR (Remote)",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "622200000",
    concept: "Other G&A Services",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "622600000",
    concept: "Other R&D Services",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "626000000",
    concept: "Essential Services (Insurances, Phone, Connectivity)",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "622610000",
    concept: "Legal related",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "622610100",
    concept: "IP",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "622620000",
    concept: "Accounting & Finance services",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "622630000",
    concept: "Accounting & Finance services",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "622640000",
    concept: "HR Related fees",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "622700000",
    concept: "Legal related",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "623000000",
    concept: "Online Marketing & Design",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "623110000",
    concept: "Online Marketing & Design",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "623400000",
    concept: "Online Marketing & Design",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "623600000",
    concept: "Online Marketing & Design",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "623610000",
    concept: "Online Marketing & Design",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "623800000",
    concept: "Online Marketing & Design",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "624100000",
    concept: "Essential Services (Insurances, Phone, Connectivity)",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "625100000",
    concept: "Travel, food & beverages",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "618510000",
    concept: "Incubateurs",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "625700000",
    concept: "Travel, food & beverages",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "625710000",
    concept: "Team events",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "626100000",
    concept: "Essential Services (Insurances, Phone, Connectivity)",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "627000000",
    concept: "Bank fees",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "627110000",
    concept: "Other Financial charges",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "628100000",
    concept: "Online Marketing & Design",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "622800000",
    concept: "Accounting & Finance services",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "628400000",
    concept: "Recruitment fees",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "628800000",
    concept: "Other charges",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "628810000",
    concept: "Accounting & Finance services",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "631200000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "631300000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "631600000",
    concept: "HR Related fees",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "631800000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "633300000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "633500000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "635110000",
    concept: "Taxes (excluding IS)",
    grandeCategorie: "Taxes & Result",
    sousCategorie: "Taxes",
  },
  {
    account: "635800000",
    concept: "HR Related fees",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "641100000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "641200000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "641212000",
    concept: "HR Related fees",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "641430000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "641300000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "641400000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "645100000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "645200000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "645300000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "645400000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "645500000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "645800000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "645810000",
    concept: "HR Related fees",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "645820000",
    concept: "HR Related fees",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "645840000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "645850000",
    concept: "HR Payroll Cost",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "647500000",
    concept: "HR Related fees",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "651600000",
    concept: "Other R&D Services",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "656000000",
    concept: "Other Financial charges",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "658000000",
    concept: "Other charges",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "661100000",
    concept: "Loan interests",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "668000000",
    concept: "Loan interests",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "671200000",
    concept: "Exceptional charges",
    grandeCategorie: "Operating Expenses (OPEX)",
    sousCategorie: "R&D Expenses",
  },
  {
    account: "675100000",
    concept: "Amortization of Intangibles assets",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "681110000",
    concept: "Amortization of Intangibles assets",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "681120000",
    concept: "Amortization of tangible assets",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "699100000",
    concept: "Income Tax Credit (CIR/CII)",
    grandeCategorie: "Operating Income & Other Products",
    sousCategorie: "Public Support & Credits",
  },
  {
    account: "706000000",
    concept: "European Projects",
    grandeCategorie: "Operating Income & Other Products",
    sousCategorie: "Public Support & Credits",
  },
  {
    account: "721000000",
    concept: "Capitalized R&D",
    grandeCategorie: "Non-Current Assets",
    sousCategorie: "Intangible Assets",
  },
  {
    account: "707000000",
    concept: "Exceptional products",
    grandeCategorie: "Operating Income & Other Products",
    sousCategorie: "Public Support & Credits",
  },
  {
    account: "740000000",
    concept: "Grant",
    grandeCategorie: "Operating Income & Other Products",
    sousCategorie: "Public Support & Credits",
  },
  {
    account: "756000000",
    concept: "Other product",
    grandeCategorie: "Operating Income & Other Products",
    sousCategorie: "Public Support & Credits",
  },
  {
    account: "758000000",
    concept: "Other product",
    grandeCategorie: "Operating Income & Other Products",
    sousCategorie: "Public Support & Credits",
  },
  {
    account: "758100000",
    concept: "Other product",
    grandeCategorie: "Operating Income & Other Products",
    sousCategorie: "Public Support & Credits",
  },
  {
    account: "766000000",
    concept: "Exceptional products",
    grandeCategorie: "Operating Income & Other Products",
    sousCategorie: "Public Support & Credits",
  },
  {
    account: "775000000",
    concept: "Exceptional products",
    grandeCategorie: "Operating Income & Other Products",
    sousCategorie: "Public Support & Credits",
  },
  {
    account: "757000000",
    concept: "Exceptional products",
    grandeCategorie: "Operating Income & Other Products",
    sousCategorie: "Public Support & Credits",
  },
  {
    account: "778000000",
    concept: "Exceptional products",
    grandeCategorie: "Operating Income & Other Products",
    sousCategorie: "Public Support & Credits",
  },
  {
    account: "791000000",
    concept: "Exceptional products",
    grandeCategorie: "Operating Income & Other Products",
    sousCategorie: "Public Support & Credits",
  },
  {
    account: "768000000",
    concept: "Financial products",
    grandeCategorie: "Operating Income & Other Products",
    sousCategorie: "Public Support & Credits",
  },
  {
    account: "486000000",
    concept: "Short term accruals debit",
    grandeCategorie: "Current Liabilities",
    sousCategorie: "Accrued Expenses / Other",
  },
];

// Helper pour retrouver le mapping d'un compte
export function getMappingForAccount(compteNum: string): MappingRule | null {
  return MAPPING_RULES.find((rule) => rule.account === compteNum) || null;
}

/**
 * Retrouve le mapping d'un compte en utilisant une logique de fallback.
 * 1. Cherche une correspondance exacte.
 * 2. Si aucune correspondance et que le compte a 10 caractères, cherche avec les 9 premiers.
 */
export function getMappingWithFallback(compteNum: string): MappingRule | null {
  const cleanedCompteNum = (compteNum || "").trim();
  if (!cleanedCompteNum) return null;

  // 1. Chercher une correspondance exacte sur le numéro de compte brut
  let mapping = getMappingForAccount(cleanedCompteNum);
  if (mapping) return mapping;

  // 2. Logique de fallback pour les comptes de 10 caractères
  if (cleanedCompteNum.length === 10) {
    const prefix = cleanedCompteNum.substring(0, 9);
    mapping = getMappingForAccount(prefix);
    if (mapping) return mapping;
  }

  return null;
}
